/*Provider bindings are generated by running cdktf get.
See https://cdk.tf/provider-generation for more details.*/
import * as aws from "./.gen/providers/aws";

/*The following providers are missing schema information and might need manual adjustments to synthesize correctly: aws.
For a more precise conversion please use the --provider flag in convert.*/
const awsVpcVpc = new aws.vpc.Vpc(this, "vpc", {
  cidr_block: "10.0.0.0/16",
});
new aws.vpc.Subnet(this, "snPrivate1", {
  availability_zone: "ap-northeast-1a",
  cidr_block: "10.0.2.0/24",
  vpc_id: awsVpcVpc.id,
});
new aws.vpc.Subnet(this, "snPrivate2", {
  availability_zone: "ap-northeast-1c",
  cidr_block: "10.0.3.0/24",
  vpc_id: awsVpcVpc.id,
});
new aws.vpc.Subnet(this, "snPublic1", {
  availability_zone: "ap-northeast-1a",
  cidr_block: "10.0.0.0/24",
  vpc_id: awsVpcVpc.id,
});
new aws.vpc.Subnet(this, "snPublic2", {
  availability_zone: "ap-northeast-1c",
  cidr_block: "10.0.1.0/24",
  vpc_id: awsVpcVpc.id,
});

