[91m[2022-09-23T23:37:54.252] [ERROR] default - [39mFound a reference that is unknown: ${aws_vpc.vpc.id} has reference "aws_vpc.vpc.id". The id was not found in ["aws_subnet.snPrivate1","aws_subnet.snPrivate2","aws_subnet.snPublic1","aws_subnet.snPublic2"] with temporary values [].
        Please leave a comment at https://cdk.tf/bugs/convert-expressions if you run into this issue.
[91m[2022-09-23T23:37:54.254] [ERROR] default - [39mFound a reference that is unknown: ${aws_vpc.vpc.id} has reference "aws_vpc.vpc.id". The id was not found in ["aws_subnet.snPrivate1","aws_subnet.snPrivate2","aws_subnet.snPublic1","aws_subnet.snPublic2"] with temporary values [].
        Please leave a comment at https://cdk.tf/bugs/convert-expressions if you run into this issue.
[91m[2022-09-23T23:37:54.254] [ERROR] default - [39mFound a reference that is unknown: ${aws_vpc.vpc.id} has reference "aws_vpc.vpc.id". The id was not found in ["aws_subnet.snPrivate1","aws_subnet.snPrivate2","aws_subnet.snPublic1","aws_subnet.snPublic2"] with temporary values [].
        Please leave a comment at https://cdk.tf/bugs/convert-expressions if you run into this issue.
[91m[2022-09-23T23:37:54.255] [ERROR] default - [39mFound a reference that is unknown: ${aws_vpc.vpc.id} has reference "aws_vpc.vpc.id". The id was not found in ["aws_subnet.snPrivate1","aws_subnet.snPrivate2","aws_subnet.snPublic1","aws_subnet.snPublic2"] with temporary values [].
        Please leave a comment at https://cdk.tf/bugs/convert-expressions if you run into this issue.
[91m[2022-09-23T23:37:54.269] [ERROR] default - [39mFound a reference that is unknown: ${aws_vpc.vpc.id} has reference "aws_vpc.vpc.id". The id was not found in ["aws_subnet.snPrivate1","aws_subnet.snPrivate2","aws_subnet.snPublic1","aws_subnet.snPublic2"] with temporary values [].
        Please leave a comment at https://cdk.tf/bugs/convert-expressions if you run into this issue.
[91m[2022-09-23T23:37:54.272] [ERROR] default - [39mFound a reference that is unknown: ${aws_vpc.vpc.id} has reference "aws_vpc.vpc.id". The id was not found in ["aws_subnet.snPrivate1","aws_subnet.snPrivate2","aws_subnet.snPublic1","aws_subnet.snPublic2"] with temporary values [].
        Please leave a comment at https://cdk.tf/bugs/convert-expressions if you run into this issue.
[91m[2022-09-23T23:37:54.274] [ERROR] default - [39mFound a reference that is unknown: ${aws_vpc.vpc.id} has reference "aws_vpc.vpc.id". The id was not found in ["aws_subnet.snPrivate1","aws_subnet.snPrivate2","aws_subnet.snPublic1","aws_subnet.snPublic2"] with temporary values [].
        Please leave a comment at https://cdk.tf/bugs/convert-expressions if you run into this issue.
[91m[2022-09-23T23:37:54.276] [ERROR] default - [39mFound a reference that is unknown: ${aws_vpc.vpc.id} has reference "aws_vpc.vpc.id". The id was not found in ["aws_subnet.snPrivate1","aws_subnet.snPrivate2","aws_subnet.snPublic1","aws_subnet.snPublic2"] with temporary values [].
        Please leave a comment at https://cdk.tf/bugs/convert-expressions if you run into this issue.
/*Provider bindings are generated by running cdktf get.
See https://cdk.tf/provider-generation for more details.*/
import * as aws from "./.gen/providers/aws";

/*The following providers are missing schema information and might need manual adjustments to synthesize correctly: aws.
For a more precise conversion please use the --provider flag in convert.*/
new aws.vpc.Subnet(this, "snPrivate1", {
  availability_zone: "ap-northeast-1a",
  cidr_block: "10.0.2.0/24",
  vpc_id: "${aws_vpc.vpc.id}",
});
new aws.vpc.Subnet(this, "snPrivate2", {
  availability_zone: "ap-northeast-1c",
  cidr_block: "10.0.3.0/24",
  vpc_id: "${aws_vpc.vpc.id}",
});
new aws.vpc.Subnet(this, "snPublic1", {
  availability_zone: "ap-northeast-1a",
  cidr_block: "10.0.0.0/24",
  vpc_id: "${aws_vpc.vpc.id}",
});
new aws.vpc.Subnet(this, "snPublic2", {
  availability_zone: "ap-northeast-1c",
  cidr_block: "10.0.1.0/24",
  vpc_id: "${aws_vpc.vpc.id}",
});

