name: "Comment a Plan on a PR"

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    name: "Terraform CDK Diff"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cdktf
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.17.0"
          cache: 'npm'
          cache-dependency-path: cdktf/package-lock.json
      - run: npm ci

      - name: Generate module and provider bindings
        run: npx cdktf get

      - name: Run Terraform CDK
        uses: hashicorp/terraform-cdk-action@v0.1.5
        with:
          terraformVersion: 1.3.0
          cdktfVersion: 0.12.2
          stackName: cdktf
          mode: plan-only
          githubToken: ${{ secrets.GITHUB_TOKEN }}
